# Generated by Django 5.2.6 on 2025-11-27 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Preferences', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Mauritian mobile number (e.g. 5XXXXXXX or +2305XXXXXXX).', regex='^(?:\\+230|230|0)?5\\d{7}$')])),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Customer', 'Customer')], max_length=10)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid Mauritian mobile number (e.g. 5XXXXXXX or +2305XXXXXXX).', regex='(?i)^[a-zA-Z]+@(gmail|hotmail|umail)\\.com$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
