# Generated by Django 5.2.6 on 2025-12-01 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid Email.', regex='(?i)^[a-zA-Z1-9]+@(gmail|hotmail|umail)\\.com$')]),
        ),
    ]
