# Generated by Django 5.2.8 on 2025-11-27 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra_toppings',
            field=models.TextField(blank=True, help_text='Comma-separated list of extra toppings.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meat_topping',
            field=models.CharField(blank=True, help_text='Selected meat topping if applicable.', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(blank=True, help_text='PAN without spaces, typically 13-19 digits', max_length=19),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cvv',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit_Card'), ('juice', 'Juice'), ('mytmob', 'MyTMob'), ('paypal', 'PayPal')], default='credit_card', max_length=20),
        ),
    ]
