# Generated by Django 5.2.8 on 2025-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_orderitem_extra_toppings_orderitem_meat_topping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Takeout', 'Takeout'), ('Dine-in', 'Dine-in')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Preparing', max_length=20),
        ),
    ]
