# Generated by Django 5.2.5 on 2025-11-27 18:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_transaction_card_name_transaction_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pick up', 'Pick Up'), ('dine in', 'Dine In')], max_length=20),
        ),
    ]
