# Generated by Django 5.2.5 on 2025-11-27 18:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_subtotal_alter_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='takeout', to='menu.order')),
            ],
        ),
    ]
