# Generated by Django 5.2.8 on 2025-11-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_order_order_type_alter_order_status'),
        ('menu', '0006_takeout'),
    ]

    operations = [
    ]
