# Generated by Django 5.2.8 on 2025-11-28 10:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_merge_20251128_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pick up', 'Pick Up'), ('dine in', 'Dine In')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
