# Generated by Django 5.2.8 on 2025-11-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menuitem_base_price_alter_order_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='base_price',
        ),
    ]
