# Generated by Django 5.2.8 on 2025-12-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_menuitem_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeout',
            name='pickup_status',
            field=models.CharField(choices=[('preparing_order', 'Preparing Order'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up')], default='preparing_order', max_length=20),
        ),
    ]
