# Generated by Django 5.2.7 on 2025-11-22 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('review_title', models.CharField(max_length=100)),
                ('review_text', models.TextField(max_length=500)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dishes_ordered', models.CharField(blank=True, max_length=255)),
                ('date_of_visit', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('would_you_recommend', models.CharField(choices=[('yes', 'Yes, absolutely!'), ('neutral', 'Not sure / Neutral'), ('no', 'No')], default='neutral', max_length=10)),
            ],
        ),
    ]
