from django import forms
from django.utils import timezone
from .models import Review


INPUT_CLASS = "w-full px-4 py-2 rounded-lg border border-gray-300 bg-white text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-400"
SELECT_CLASS = "w-full h-9 pl-3 pr-8 rounded-lg bg-gray-100 border border-gray-300 text-sm text-black"


class ReviewForm(forms.ModelForm):
    """Form for submitting a Review.

    Uses the Review model and applies sensible widgets, placeholders and
    lightweight validation (max lengths, date not in the future).
    """

    # enforce exactly 5 rating choices at the form layer to avoid extra/empty choices
    RATING_CHOICES = [(i, f"{i} Star{'s' if i>1 else ''}") for i in range(1, 6)]

    # override the autogenerated rating field with an explicit ChoiceField
    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect, required=True)

    class Meta:
        model = Review
        fields = [
            'user_name',
            'email',
            'review_title',
            'review_text',
            'rating',
            'dishes_ordered',
            'date_of_visit',
            'would_you_recommend',
        ]
        labels = {
            'user_name': 'Your Name',
            'review_title': 'Review Title',
            'review_text': 'Your Review',
            'dishes_ordered': 'Dishes You Ordered',
            'date_of_visit': 'Date of Visit',
            'would_you_recommend': 'Would you recommend us to friends?',
        }
        help_texts = {
            'review_text': 'Share your dining experience, food quality, service, and atmosphere (max 500 chars).',
            'dishes_ordered': 'Separate multiple items with commas (optional).',
        }
        widgets = {
            'user_name': forms.TextInput(attrs={'class': INPUT_CLASS, 'placeholder': 'Enter your full name', 'maxlength': 100}),
            'email': forms.EmailInput(attrs={'class': INPUT_CLASS, 'placeholder': 'Enter your email address', 'maxlength': 100}),
            'review_title': forms.TextInput(attrs={'class': INPUT_CLASS, 'placeholder': 'Give your review a title', 'maxlength': 100}),
            'review_text': forms.Textarea(attrs={
                'class': INPUT_CLASS + ' h-32 resize-y',
                'placeholder': 'Share your dining experience, food quality, service, and atmosphere...',
                'maxlength': 500,
                'rows': 6,
            }),
            'rating': forms.Select(attrs={'class': SELECT_CLASS}),
            'dishes_ordered': forms.TextInput(attrs={'class': INPUT_CLASS, 'placeholder': 'e.g., Pasta Carbonara, Caesar Salad, Tiramisu', 'maxlength': 255}),
            'date_of_visit': forms.DateInput(attrs={'class': INPUT_CLASS, 'type': 'date'}),
            'would_you_recommend': forms.Select(attrs={'class': SELECT_CLASS}),
        }

    def clean_review_text(self):
        text = self.cleaned_data.get('review_text', '')
        if len(text) > 500:
            raise forms.ValidationError('Review cannot be longer than 500 characters.')
        return text

    def clean_date_of_visit(self):
        date = self.cleaned_data.get('date_of_visit')
        if date and date > timezone.localdate():
            raise forms.ValidationError('Date of visit cannot be in the future.')
        return date

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # extra validation could go here (e.g. domain checks)
        return email