# Generated by Django 5.2.6 on 2025-12-02 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Mauritian mobile number (e.g. 5XXXXXXX or +2305XXXXXXX).', regex='^(?:\\+230|230|0)?5\\d{7}$')])),
                ('email', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Email.', regex='(?i)^[a-z0-9._%+-]+@(gmail|hotmail|umail)\\.com$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
